# Generated by Django 6.1 on 2026-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, help_text='Last known FonePay payment status (pending, COMPLETED, failed).', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='prn',
            field=models.CharField(blank=True, help_text='FonePay Payment Reference Number for dynamic-QR transactions.', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='Transaction/payment ID from the payment gateway (e.g. FonePay trace ID).', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Manually confirmed for COD/WhatsApp/Instagram orders; set automatically for gateway payments.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('fonepay', 'FonePay'), ('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20),
        ),
    ]
