# Generated by Django 6.1 on 2026-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_payment_status_order_prn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prn',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='Unique transaction identifier for gateway payments (e.g. eSewa transaction_uuid).', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='Transaction/payment ID from the payment gateway (e.g. eSewa transaction_code).', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, help_text='Last known gateway payment status (pending, COMPLETED, failed).', max_length=20),
        ),
    ]
