# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_prn_order_transaction_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(
                blank=True,
                help_text='Customer email for order and payment confirmation emails.',
                max_length=254,
            ),
        ),
    ]
