# Generated by Django 6.1 on 2026-08-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated']},
        ),
    ]
