# Generated by Django 6.1 on 2026-09-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('fonepay', 'Fonepay'), ('khalti', 'Khalti')], max_length=20),
        ),
    ]
